source "https://rubygems.org"

ruby "4.0.5"

gem "rails", "8.1.3"
gem "pg", "1.5.9"
gem "puma", "7.0.2"
gem "solid_queue", "1.4.0"
gem "pundit", "2.5.2"
gem "redis", "5.4.1"

group :development, :test do
  gem "rspec-rails", "8.0.4"
end
